//! Embedded source inventory only: no native functions, types, Engine or VM.
macro_rules! sources {
    ($($name:literal => $file:literal),* $(,)?) => { &[$(($name,
        include_str!(concat!("../modules/std/", $file, ".telora")))),*] };
}
pub const BUILTINS: &[(&str, &str)] = sources![
    "std" => "lib",
    "std/_codec" => "_codec",
    "std/_entry" => "_entry",
    "std/_entry/collection" => "_entry/collection",
    "std/_entry/transform" => "_entry/transform",
    "std/_parse" => "_parse",
    "std/_rt" => "_rt",
    "std/argv" => "argv",
    "std/array" => "array",
    "std/blame" => "blame",
    "std/codec" => "codec",
    "std/dict" => "dict",
    "std/dyn" => "dyn",
    "std/eq" => "eq",
    "std/fmt" => "fmt",
    "std/hash" => "hash",
    "std/http" => "http",
    "std/json" => "json",
    "std/option" => "option",
    "std/path" => "path",
    "std/prelude" => "prelude",
    "std/regex" => "regex",
    "std/result" => "result",
    "std/string" => "string",
    "std/test" => "test",
    "std/toml" => "toml",
    "std/transform_service" => "transform_service",
    "std/type_desc" => "type_desc",
    "std/type_property" => "type_property",
    "std/value" => "value",
    "std/yaml" => "yaml",
];

/// Trusted source admission assigns ABI identities before any source is read.
/// Only this inventory layer deals with module names; consumers use numeric IDs.
pub fn native_module(name: &str) -> Option<crate::mir::NativeModule> {
    use crate::mir::{NativeModule, NativeTypeRule as R, TypeConstructor as T, TypeFunction as F};
    let (id, types) = match name {
        "std/prelude" => (
            18,
            vec![
                (0, R::Primitive(T::Type)),
                (1, R::Primitive(T::Dyn)),
                (2, R::Primitive(T::Never)),
                (3, R::Primitive(T::Tuple)),
                (4, R::Primitive(T::Int)),
                (5, R::Primitive(T::Float)),
                (6, R::Primitive(T::String)),
                (7, R::Primitive(T::Bytes)),
                (8, R::Primitive(T::Bool)),
                (9, R::Primitive(T::PropertyTarget)),
                (10, R::Constructor(F::Array)),
                (11, R::Constructor(F::Dict)),
                (12, R::Constructor(F::TypeOf)),
                (13, R::Constructor(F::Unchecked)),
                (14, R::Constructor(F::Tuple)),
                (15, R::Constructor(F::Func)),
                (16, R::Constructor(F::Option)),
                (17, R::Constructor(F::Result)),
                (18, R::Constructor(F::FoldControl)),
                (19, R::Constructor(F::Property)),
            ],
        ),
        "std/regex" => (19, vec![(0, R::Opaque)]),
        "std/fmt" => (20, vec![(1, R::Opaque)]),
        "std/hash" => (16, vec![(3, R::Opaque)]),
        "std/test" => (33, vec![(0, R::Opaque)]),
        "std/blame" => (
            crate::mir::NativeTypeId::BLAME_ERROR.module,
            vec![(crate::mir::NativeTypeId::BLAME_ERROR.slot, R::Opaque)],
        ),
        "std/eq" => (1, vec![]),
        "std/dyn" => (2, vec![]),
        "std/type_desc" => (3, vec![]),
        "std/_codec" => (4, vec![]),
        "std/array" => (5, vec![]),
        "std/dict" => (6, vec![]),
        "std/string" => (7, vec![]),
        "std/path" => (8, vec![]),
        "std/toml" => (9, vec![]),
        "std/codec" => (13, vec![]),
        "std/option" => (14, vec![]),
        "std/result" => (15, vec![]),
        "std/json" => (17, vec![]),
        "std/argv" => (22, vec![]),
        "std/value" => (23, vec![]),
        "std/yaml" => (24, vec![]),
        "std/type_property" => (25, vec![]),
        "std/_rt" => (26, vec![]),
        "std/_parse" => (27, vec![]),
        _ => return None,
    };
    Some(NativeModule { id, types })
}
