//! Independent Wasm backend. No interpreter or native-backend fallback.
#[cfg(test)]
extern crate alloc;
pub mod abi;
mod aggregates;
mod array_build;
mod array_ops;
pub mod artifact;
pub mod bundle;
mod capture;
mod capture_values;
mod checks;
mod codec_arrays;
mod codec_decode;
mod codec_decode_arrays;
mod codec_decode_enum;
mod codec_decode_nominal;
mod codec_decode_record;
mod codec_decode_tuple;
mod codec_decode_untagged;
mod codec_display;
mod codec_enums;
mod codec_names;
mod codec_ops;
mod codec_plan;
mod codec_properties;
mod codec_records;
mod codegen;
pub mod collection;
mod compose;
mod data_input;
mod data_parse_ops;
pub mod debug;
mod debug_repr;
pub mod diagnostic_output;
mod diagnostics;
mod dict_build;
mod dict_literals;
mod dict_ops;
mod dictionaries;
mod dynamic_construct;
mod dynamic_fields;
mod dynamic_kind;
mod dynamic_members;
mod dynamic_named_field;
mod dynamic_ops;
mod dynamic_sequences;
mod dynamic_tuples;
mod dynamic_variants;
mod emit;
mod enums;
mod equality;
mod equality_format;
mod equality_plan;
mod format_ops;
mod fuel_quota;
mod function_names;
mod functions;
mod guest_input;
mod hash_ops;
mod input;
mod input_heap;
mod input_types;
mod interpreters;
mod json_ops;
mod local_instances;
mod natives;
pub mod object;
mod output;
mod parse_ops;
mod parse_plan;
mod parse_record;
mod path_ops;
mod patterns;
mod plan;
mod properties;
mod records;
mod reflection_collections;
mod reflection_data;
mod reflection_ops;
mod regex_ops;
mod regex_property;
mod service_abi;
mod service_reply;
mod template;
mod value_origins;
use telora_wasm_shared::abi as runtime_abi;
pub mod publication;
mod scalars;
mod sequences;
pub mod session;
mod stack_values;
mod string_ops;
mod tail_calls;
mod template_ops;
mod test_description;
pub mod testing;
pub mod transform_service;
pub mod transport;
mod transport_heap;

pub use codegen::{compile_check, compile_executable, compile_service};

#[cfg(test)]
mod tests;
