//! Semantic syntax kinds consumed by HIR lowering.
#[derive(Copy, Clone, PartialEq, Eq)]
#[allow(dead_code)]
pub enum Rule {
    Argument,
    Arguments,
    ArrayExpr,
    ArrayItem,
    BinaryExpr,
    Binding,
    Block,
    Body,
    Braced,
    BytesExpr,
    CallExpr,
    Closure,
    ConcatExpression,
    ConstructorPattern,
    Contract,
    ContractArgument,
    ContractArray,
    ContractExpr,
    ContractPath,
    CtrlBlock,
    DataBinding,
    DataFormat,
    DataImport,
    DeclBinding,
    Decorator,
    DecoratorPath,
    DefBinding,
    DictExpr,
    DictField,
    DictItem,
    DoExpr,
    DotPostfixExpr,
    DotSuffix,
    EnumInitializer,
    EnumInitializerVariant,
    Error,
    Expression,
    FieldProjectionEntry,
    FieldProjectionSuffix,
    FloatExpr,
    FloatPattern,
    FunctionContract,
    IdentifierPattern,
    IfExpr,
    IfLetExpr,
    ImplBinding,
    ImplMember,
    IndexExpr,
    IntExpr,
    IntPattern,
    Interpolation,
    InterpreterIntrinsic,
    LegacyInterpreterExpr,
    LetBinding,
    LetElseBinding,
    LetPatternBinding,
    MatchArm,
    MatchExpr,
    MetadataSuffix,
    ModuleBody,
    ModuleDeclaration,
    NamedIntrinsic,
    NativeBinding,
    NativeTypeBinding,
    Parameter,
    Parameters,
    ParenExpr,
    Pattern,
    PipelineExpr,
    PostfixIntrinsicSuffix,
    Primary,
    Program,
    ProjectionSuffix,
    PropagateExpr,
    ReturnExpr,
    SectionArguments,
    SectionExpr,
    SpreadExpr,
    SpreadItem,
    StringExpr,
    StringLiteral,
    StringPart,
    StringPattern,
    StringTextPart,
    StaticPath,
    StaticPathExpr,
    StructInitializer,
    StructInitializerField,
    StructPattern,
    StructPatternField,
    TraitBinding,
    TraitBound,
    TraitMember,
    TuplePattern,
    TypeApplyExpr,
    TypeArgument,
    TypeArguments,
    TypeBinding,
    TypeInitializer,
    TypeParameter,
    TypeParameters,
    TypeScheme,
    UnaryExpr,
    UnitContract,
    UseBinding,
    UseItem,
    UseItems,
    UsePath,
    UseSelector,
    VariableExpr,
    Visibility,
}

impl std::fmt::Debug for Rule {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Rule::Argument => write!(f, "argument"),
            Rule::Arguments => write!(f, "arguments"),
            Rule::ArrayExpr => write!(f, "array_expr"),
            Rule::ArrayItem => write!(f, "array_item"),
            Rule::BinaryExpr => write!(f, "binary_expr"),
            Rule::Binding => write!(f, "binding"),
            Rule::Block => write!(f, "block"),
            Rule::Body => write!(f, "body"),
            Rule::Braced => write!(f, "braced"),
            Rule::BytesExpr => write!(f, "bytes_expr"),
            Rule::CallExpr => write!(f, "call_expr"),
            Rule::Closure => write!(f, "closure"),
            Rule::ConcatExpression => write!(f, "concat_expression"),
            Rule::ConstructorPattern => write!(f, "constructor_pattern"),
            Rule::Contract => write!(f, "contract"),
            Rule::ContractArgument => write!(f, "contract_argument"),
            Rule::ContractArray => write!(f, "contract_array"),
            Rule::ContractExpr => write!(f, "contract_expr"),
            Rule::ContractPath => write!(f, "contract_path"),
            Rule::CtrlBlock => write!(f, "ctrl_block"),
            Rule::DataBinding => write!(f, "data_binding"),
            Rule::DataFormat => write!(f, "data_format"),
            Rule::DataImport => write!(f, "data_import"),
            Rule::DeclBinding => write!(f, "decl_binding"),
            Rule::Decorator => write!(f, "decorator"),
            Rule::DecoratorPath => write!(f, "decorator_path"),
            Rule::DefBinding => write!(f, "def_binding"),
            Rule::DictExpr => write!(f, "dict_expr"),
            Rule::DictField => write!(f, "dict_field"),
            Rule::DictItem => write!(f, "dict_item"),
            Rule::DoExpr => write!(f, "do_expr"),
            Rule::DotPostfixExpr => write!(f, "dot_postfix_expr"),
            Rule::DotSuffix => write!(f, "dot_suffix"),
            Rule::EnumInitializer => write!(f, "enum_initializer"),
            Rule::EnumInitializerVariant => write!(f, "enum_initializer_variant"),
            Rule::Error => write!(f, "error"),
            Rule::Expression => write!(f, "expression"),
            Rule::FieldProjectionEntry => write!(f, "field_projection_entry"),
            Rule::FieldProjectionSuffix => write!(f, "field_projection_suffix"),
            Rule::FloatExpr => write!(f, "float_expr"),
            Rule::FloatPattern => write!(f, "float_pattern"),
            Rule::FunctionContract => write!(f, "function_contract"),
            Rule::IdentifierPattern => write!(f, "identifier_pattern"),
            Rule::IfExpr => write!(f, "if_expr"),
            Rule::IfLetExpr => write!(f, "if_let_expr"),
            Rule::ImplBinding => write!(f, "impl_binding"),
            Rule::ImplMember => write!(f, "impl_member"),
            Rule::IndexExpr => write!(f, "index_expr"),
            Rule::IntExpr => write!(f, "int_expr"),
            Rule::IntPattern => write!(f, "int_pattern"),
            Rule::Interpolation => write!(f, "interpolation"),
            Rule::InterpreterIntrinsic => write!(f, "interpreter_intrinsic"),
            Rule::LegacyInterpreterExpr => write!(f, "legacy_interpreter_expr"),
            Rule::LetBinding => write!(f, "let_binding"),
            Rule::LetElseBinding => write!(f, "let_else_binding"),
            Rule::LetPatternBinding => write!(f, "let_pattern_binding"),
            Rule::MatchArm => write!(f, "match_arm"),
            Rule::MatchExpr => write!(f, "match_expr"),
            Rule::MetadataSuffix => write!(f, "metadata_suffix"),
            Rule::ModuleBody => write!(f, "module_body"),
            Rule::ModuleDeclaration => write!(f, "module_declaration"),
            Rule::NamedIntrinsic => write!(f, "named_intrinsic"),
            Rule::NativeBinding => write!(f, "native_binding"),
            Rule::NativeTypeBinding => write!(f, "native_type_binding"),
            Rule::Parameter => write!(f, "parameter"),
            Rule::Parameters => write!(f, "parameters"),
            Rule::ParenExpr => write!(f, "paren_expr"),
            Rule::Pattern => write!(f, "pattern"),
            Rule::PipelineExpr => write!(f, "pipeline_expr"),
            Rule::PostfixIntrinsicSuffix => write!(f, "postfix_intrinsic_suffix"),
            Rule::Primary => write!(f, "primary"),
            Rule::Program => write!(f, "program"),
            Rule::ProjectionSuffix => write!(f, "projection_suffix"),
            Rule::PropagateExpr => write!(f, "propagate_expr"),
            Rule::ReturnExpr => write!(f, "return_expr"),
            Rule::SectionArguments => write!(f, "section_arguments"),
            Rule::SectionExpr => write!(f, "section_expr"),
            Rule::SpreadExpr => write!(f, "spread_expr"),
            Rule::SpreadItem => write!(f, "spread_item"),
            Rule::StringExpr => write!(f, "string_expr"),
            Rule::StringLiteral => write!(f, "string_literal"),
            Rule::StringPart => write!(f, "string_part"),
            Rule::StringPattern => write!(f, "string_pattern"),
            Rule::StringTextPart => write!(f, "string_text_part"),
            Rule::StaticPath => write!(f, "static_path"),
            Rule::StaticPathExpr => write!(f, "static_path_expr"),
            Rule::StructInitializer => write!(f, "struct_initializer"),
            Rule::StructInitializerField => write!(f, "struct_initializer_field"),
            Rule::StructPattern => write!(f, "struct_pattern"),
            Rule::StructPatternField => write!(f, "struct_pattern_field"),
            Rule::TraitBinding => write!(f, "trait_binding"),
            Rule::TraitBound => write!(f, "trait_bound"),
            Rule::TraitMember => write!(f, "trait_member"),
            Rule::TuplePattern => write!(f, "tuple_pattern"),
            Rule::TypeApplyExpr => write!(f, "type_apply_expr"),
            Rule::TypeArgument => write!(f, "type_argument"),
            Rule::TypeArguments => write!(f, "type_arguments"),
            Rule::TypeBinding => write!(f, "type_binding"),
            Rule::TypeInitializer => write!(f, "type_initializer"),
            Rule::TypeParameter => write!(f, "type_parameter"),
            Rule::TypeParameters => write!(f, "type_parameters"),
            Rule::TypeScheme => write!(f, "type_scheme"),
            Rule::UnaryExpr => write!(f, "unary_expr"),
            Rule::UnitContract => write!(f, "unit_contract"),
            Rule::UseBinding => write!(f, "use_binding"),
            Rule::UseItem => write!(f, "use_item"),
            Rule::UseItems => write!(f, "use_items"),
            Rule::UsePath => write!(f, "use_path"),
            Rule::UseSelector => write!(f, "use_selector"),
            Rule::VariableExpr => write!(f, "variable_expr"),
            Rule::Visibility => write!(f, "visibility"),
        }
    }
}
