[package]
name = "telora-wasm"
version.workspace = true
edition.workspace = true

[dependencies]
telora-data = { path = "../telora-data", features = ["serde"] }
telora-wasm-shared = { path = "../telora-wasm-shared" }
telora-core = { path = "../telora-core" }
wasm-encoder = "0.259"
wasmparser = "0.259"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wasmi = "2"
