//! Explicit developer tool; normal builds consume the checked-in parser modules.
use std::{fs, path::PathBuf};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("..");
    let temporary = std::env::temp_dir().join(format!("telora-parser-gen-{}", std::process::id()));
    fs::create_dir(&temporary)?;
    let result = generate(&root, &temporary);
    fs::remove_dir_all(&temporary)?;
    result
}

fn generate(
    root: &std::path::Path,
    temporary: &std::path::Path,
) -> Result<(), Box<dyn std::error::Error>> {
    for language in ["json", "toml", "yaml"] {
        let root = root.join("telora-data/src/syntax");
        let grammar = root.join(language).join("grammar.llw");
        let success = lelwel::compile(
            grammar.to_str().unwrap(),
            temporary.to_str().unwrap(),
            false,
            false,
            0,
            false,
            true,
        )?;
        if !success {
            return Err(format!("invalid grammar: {}", grammar.display()).into());
        }
        let generated = fs::read_to_string(temporary.join("generated.rs"))?;
        let mut module = String::from(
            "// @generated by cargo run -p telora-parser-gen; do not edit.\n#![allow(unused_variables)]\n\nuse super::lexer::{Token, tokenize};\nuse codespan_reporting::diagnostic::Label;\npub type Diagnostic = codespan_reporting::diagnostic::Diagnostic<()>;\n\n",
        );
        module.push_str("use alloc::{string::String, vec::Vec};\n");
        module.push_str(&generated.replace("std::", "core::"));
        // Callbacks are a real child module and can access parser state without
        // exposing generated implementation details outside this module.
        module.push_str("\nmod support;\n");
        let output = root.join(language).join("parser.rs");
        fs::write(&output, module)?;
        let status = std::process::Command::new("rustfmt")
            .args(["--edition", "2024", "--config", "skip_children=true"])
            .arg(&output)
            .status()?;
        if !status.success() {
            return Err(format!("rustfmt failed for {}", output.display()).into());
        }
    }
    Ok(())
}
