// @generated by cargo run -p telora-parser-gen; do not edit.
#![allow(unused_variables)]

use super::lexer::{Token, tokenize};
use codespan_reporting::diagnostic::Label;
pub type Diagnostic = codespan_reporting::diagnostic::Diagnostic<()>;

use alloc::{string::String, vec::Vec};
// generated by lelwel 0.10.4

macro_rules! err {
    [$self:expr, $msg:literal] => {
        $self.create_diagnostic($self.span(), String::from($msg))
    }
}

#[derive(Copy, Clone, PartialEq, Eq)]
#[allow(dead_code)]
pub enum Rule {
    Array,
    ArrayTail,
    Document,
    Error,
    InlineTable,
    Key,
    KeyPart,
    KeyValue,
    Statement,
    TableTail,
    Value,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, Ord, PartialOrd)]
pub struct NodeRef(pub usize);

impl NodeRef {
    #[allow(dead_code)]
    pub const ROOT: NodeRef = NodeRef(0);
}

#[cfg(target_pointer_width = "64")]
#[derive(Copy, Clone)]
pub struct CstIndex([u8; 6]);

#[cfg(any(target_pointer_width = "16", target_pointer_width = "32"))]
#[derive(Copy, Clone)]
pub struct CstIndex(usize);

impl core::fmt::Debug for CstIndex {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> Result<(), core::fmt::Error> {
        usize::from(*self).fmt(f)
    }
}

impl From<CstIndex> for usize {
    #[cfg(target_pointer_width = "64")]
    #[inline]
    fn from(value: CstIndex) -> Self {
        let [b0, b1, b2, b3, b4, b5] = value.0;
        usize::from_le_bytes([b0, b1, b2, b3, b4, b5, 0, 0])
    }
    #[cfg(any(target_pointer_width = "16", target_pointer_width = "32"))]
    #[inline]
    fn from(value: CstIndex) -> Self {
        value.0
    }
}
impl From<usize> for CstIndex {
    #[cfg(target_pointer_width = "64")]
    #[inline]
    fn from(value: usize) -> Self {
        let [b0, b1, b2, b3, b4, b5, b6, b7] = value.to_le_bytes();
        debug_assert!(b6 == 0 && b7 == 0);
        Self([b0, b1, b2, b3, b4, b5])
    }
    #[cfg(any(target_pointer_width = "16", target_pointer_width = "32"))]
    #[inline]
    fn from(value: usize) -> Self {
        Self(value)
    }
}

/// Type of a node in the CST.
///
/// The nodes for rules contain the offset to their last child node.
/// The nodes for tokens contain an index to their span.
///
/// On 64 bit platforms offsets and indices are stored as 48 bit integers.
/// This allows the `Node` type to be 8 bytes in size as long as the `Rule`
/// and `Token` enums are one byte in size.
#[derive(Debug, Copy, Clone)]
pub enum Node {
    Rule(Rule, CstIndex),
    Token(Token, CstIndex),
}

#[derive(Clone, Copy)]
struct MarkOpened(usize);
#[derive(Clone, Copy)]
struct MarkClosed(usize);
#[derive(Clone)]
struct MarkTruncation {
    node_count: usize,
    token_count: usize,
    non_skip_len: usize,
}

/// An iterator for child nodes of a CST node.
#[derive(Default)]
pub struct CstChildren<'a> {
    iter: core::slice::Iter<'a, Node>,
    offset: usize,
}
impl Iterator for CstChildren<'_> {
    type Item = NodeRef;

    fn next(&mut self) -> Option<Self::Item> {
        let offset = self.offset;
        self.offset += 1;
        if let Some(node) = self.iter.next() {
            if let Node::Rule(_, end_offset) = node {
                let end_offset = usize::from(*end_offset);
                if end_offset > 0 {
                    self.iter.nth(end_offset.saturating_sub(1));
                    self.offset += end_offset;
                }
            }
            Some(NodeRef(offset))
        } else {
            None
        }
    }
}

pub type Span = core::ops::Range<usize>;

#[derive(Debug)]
pub struct CstData {
    spans: Vec<Span>,
    nodes: Vec<Node>,
    token_count: usize,
    non_skip_len: usize,
}
#[allow(dead_code)]
impl CstData {
    fn new(spans: Vec<Span>) -> Self {
        let nodes = Vec::with_capacity(spans.len() * 2);
        Self {
            spans,
            nodes,
            token_count: 0,
            non_skip_len: 0,
        }
    }
    fn open(&mut self) -> MarkOpened {
        let mark = MarkOpened(self.nodes.len());
        self.nodes.push(Node::Rule(Rule::Error, 0.into()));
        self.non_skip_len = self.nodes.len();
        mark
    }
    fn close(&mut self, mark: MarkOpened, rule: Rule) -> MarkClosed {
        let len = self.non_skip_len - 1;
        self.nodes[mark.0] = Node::Rule(
            rule,
            if mark.0 > len {
                self.non_skip_len += mark.0 - len;
                0
            } else {
                len - mark.0
            }
            .into(),
        );
        MarkClosed(mark.0)
    }
    fn close_root(&mut self, mark: MarkOpened, rule: Rule) -> MarkClosed {
        self.nodes[mark.0] = Node::Rule(rule, (self.nodes.len() - 1 - mark.0).into());
        MarkClosed(mark.0)
    }
    fn advance(&mut self, token: Token, skip: bool) {
        self.nodes.push(Node::Token(token, self.token_count.into()));
        self.token_count += 1;
        if !skip {
            self.non_skip_len = self.nodes.len();
        }
    }
    fn open_before(&mut self, mark: MarkClosed) -> MarkOpened {
        self.nodes.insert(mark.0, Node::Rule(Rule::Error, 0.into()));
        self.non_skip_len += 1;
        MarkOpened(mark.0)
    }
    fn mark(&self) -> MarkClosed {
        MarkClosed(self.nodes.len())
    }
    fn mark_truncation(&self) -> MarkTruncation {
        MarkTruncation {
            node_count: self.nodes.len(),
            token_count: self.token_count,
            non_skip_len: self.non_skip_len,
        }
    }
    fn truncate(&mut self, mark: MarkTruncation) {
        self.nodes.truncate(mark.node_count);
        self.token_count = mark.token_count;
        self.non_skip_len = mark.non_skip_len;
    }
    pub fn children(&self, node_ref: NodeRef) -> CstChildren<'_> {
        let iter = if let Node::Rule(_, end_offset) = self.nodes[node_ref.0] {
            self.nodes[node_ref.0 + 1..node_ref.0 + usize::from(end_offset) + 1].iter()
        } else {
            core::slice::Iter::default()
        };
        CstChildren {
            iter,
            offset: node_ref.0 + 1,
        }
    }
    pub fn get(&self, node_ref: NodeRef) -> Node {
        self.nodes[node_ref.0]
    }
    pub fn span(&self, node_ref: NodeRef) -> Span {
        fn find_token<'a>(mut iter: impl Iterator<Item = &'a Node>) -> Option<usize> {
            iter.find_map(|node| match node {
                Node::Rule(..) => None,
                Node::Token(_, idx) => Some(usize::from(*idx)),
            })
        }
        match self.nodes[node_ref.0] {
            Node::Token(_, idx) => self.spans[usize::from(idx)].clone(),
            Node::Rule(_, end_offset) => {
                let end = node_ref.0 + usize::from(end_offset);
                let first = find_token(self.nodes[node_ref.0 + 1..=end].iter());
                let last = find_token(self.nodes[node_ref.0 + 1..=end].iter().rev());
                if let (Some(first), Some(last)) = (first, last) {
                    self.spans[first].start..self.spans[last].end
                } else {
                    let offset = find_token(self.nodes[..node_ref.0].iter().rev())
                        .map_or(0, |before| self.spans[before].end);
                    offset..offset
                }
            }
        }
    }
    pub fn match_token(&self, node_ref: NodeRef, matched_token: Token) -> Option<Span> {
        match self.nodes[node_ref.0] {
            Node::Token(token, idx) if token == matched_token => {
                Some(self.spans[usize::from(idx)].clone())
            }
            _ => None,
        }
    }
    pub fn match_rule(&self, node_ref: NodeRef, matched_rule: Rule) -> bool {
        matches!(self.nodes[node_ref.0], Node::Rule(rule, _) if rule == matched_rule)
    }
}

/// A concrete syntax tree (CST) type.
///
/// Nodes are laid out linearly in memory.
/// Spans for tokens are directly stored in the `spans` vector.
/// Spans for rule nodes are calculated based on their contained token nodes.
///
/// # Example
/// This syntax tree
/// ```text
/// foo
///   bar
///     A
///     B
///   C
/// ```
/// will have the following `nodes` vector.
/// ```text
/// [
///    Node::Rule(Rule::Foo, 4),
///    Node::Rule(Rule::Bar, 2),
///    Node::Token(Token::A, 0),
///    Node::Token(Token::B, 1),
///    Node::Token(Token::C, 2),
/// ]
/// ```
#[derive(Debug)]
pub struct Cst<'a> {
    source: &'a str,
    data: CstData,
}
#[allow(dead_code)]
impl<'a> Cst<'a> {
    pub fn source(&self) -> &'a str {
        self.source
    }
    pub fn into_data(self) -> CstData {
        self.data
    }
    /// Returns an iterator over the children of the node referenced by `node_ref`.
    pub fn children(&self, node_ref: NodeRef) -> CstChildren<'_> {
        self.data.children(node_ref)
    }
    /// Returns the node referenced by `node_ref`.
    pub fn get(&self, node_ref: NodeRef) -> Node {
        self.data.get(node_ref)
    }
    /// Returns the span for the node referenced by `node_ref`.
    ///
    /// For rules the span is calculated based on the first and last token.
    /// If there are no tokens the function returns `None`.
    pub fn span(&self, node_ref: NodeRef) -> Span {
        self.data.span(node_ref)
    }
    /// Returns the slice and span of the node referenced by `node_ref` if it matches `matched_token`.
    pub fn match_token(&self, node_ref: NodeRef, matched_token: Token) -> Option<(&'a str, Span)> {
        self.data
            .match_token(node_ref, matched_token)
            .map(|span| (&self.source[span.clone()], span))
    }
    /// Checks if the node referenced by `node_ref` matches `matched_rule`.
    pub fn match_rule(&self, node_ref: NodeRef, matched_rule: Rule) -> bool {
        self.data.match_rule(node_ref, matched_rule)
    }
    /// Returns the source text corresponding to the span index
    pub fn span_text(&self, span_idx: CstIndex) -> &'a str {
        &self.source[self.data.spans[usize::from(span_idx)].clone()]
    }
}

impl core::fmt::Display for Cst<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        const DEPTH: &str = "    ";
        fn rec(
            cst: &Cst<'_>,
            f: &mut core::fmt::Formatter<'_>,
            node_ref: NodeRef,
            indent: usize,
        ) -> core::fmt::Result {
            match cst.get(node_ref) {
                Node::Rule(rule, _) => {
                    let span = cst.span(node_ref);
                    writeln!(f, "{}{rule:?} [{span:?}]", DEPTH.repeat(indent))?;
                    for child_node_ref in cst.children(node_ref) {
                        rec(cst, f, child_node_ref, indent + 1)?;
                    }
                    Ok(())
                }
                Node::Token(token, idx) => {
                    let span = &cst.data.spans[usize::from(idx)];
                    writeln!(
                        f,
                        "{}{:?} {:?} [{:?}]",
                        DEPTH.repeat(indent),
                        token,
                        &cst.source[span.clone()],
                        span,
                    )
                }
            }
        }
        rec(self, f, NodeRef::ROOT, 0)
    }
}

impl core::fmt::Debug for Rule {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Rule::Array => write!(f, "array"),
            Rule::ArrayTail => write!(f, "array_tail"),
            Rule::Document => write!(f, "document"),
            Rule::Error => write!(f, "error"),
            Rule::InlineTable => write!(f, "inline_table"),
            Rule::Key => write!(f, "key"),
            Rule::KeyPart => write!(f, "key_part"),
            Rule::KeyValue => write!(f, "key_value"),
            Rule::Statement => write!(f, "statement"),
            Rule::TableTail => write!(f, "table_tail"),
            Rule::Value => write!(f, "value"),
        }
    }
}

macro_rules! expect {
    ($token:ident, $msg:literal, $self:expr, $diags:expr) => {
        if let Token::$token = $self.current {
            $self.advance(false, $diags);
        } else {
            $self.error($diags, err![$self, $msg]);
        }
    };
}
#[allow(unused_macros)]
macro_rules! try_expect {
    ($token:ident, $msg:literal, $self:expr, $diags:expr) => {
        if let Token::$token = $self.current {
            $self.advance(false, $diags);
        } else {
            if $self.in_ordered_choice {
                return None;
            }
            $self.error($diags, err![$self, $msg]);
        }
    };
}

struct ParserState {
    pos: usize,
    current: Token,
    truncation_mark: MarkTruncation,
    diag_count: usize,
}
pub struct Parser<'a> {
    cst: Cst<'a>,
    tokens: Vec<Token>,
    pos: usize,
    current: Token,
    end_of_input: Token,
    max_offset: usize,
    #[allow(dead_code)]
    context: <Self as ParserCallbacks<'a>>::Context,
    error_node: Option<MarkOpened>,
    #[allow(dead_code)]
    in_ordered_choice: bool,
    error_since_advance: bool,
}
#[allow(clippy::while_let_loop, dead_code, unused_parens)]
impl<'a> Parser<'a> {
    fn active_error(&self) -> bool {
        self.error_node.is_some() || self.error_since_advance
    }
    fn error(
        &mut self,
        diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>,
        diag: <Self as ParserCallbacks<'a>>::Diagnostic,
    ) {
        if self.active_error() {
            return;
        }
        self.error_since_advance = true;
        diags.push(diag);
    }
    fn advance(&mut self, error: bool, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) {
        if !error {
            self.close_error_node(diags);
            self.error_since_advance = false;
        }
        self.cst.data.advance(self.current, false);
        loop {
            self.pos += 1;
            match self.tokens.get(self.pos) {
                Some(token @ (Token::Error | Token::Whitespace | Token::Comment)) => {
                    self.cst.data.advance(*token, true);
                    continue;
                }
                Some(token) if self.predicate_skip(*token) => {
                    self.cst.data.advance(*token, true);
                    continue;
                }
                Some(token) => {
                    self.current = *token;
                    break;
                }
                None => {
                    self.current = self.end_of_input;
                    break;
                }
            }
        }
    }
    fn is_skipped(token: Token) -> bool {
        matches!(token, Token::Error | Token::Whitespace | Token::Comment)
    }
    fn init_skip(&mut self) {
        loop {
            match self.tokens.get(self.pos) {
                Some(token @ (Token::Error | Token::Whitespace | Token::Comment)) => {
                    self.pos += 1;
                    self.cst.data.advance(*token, true);
                    continue;
                }
                Some(token) if self.predicate_skip(*token) => {
                    self.pos += 1;
                    self.cst.data.advance(*token, true);
                    continue;
                }
                Some(token) => {
                    self.current = *token;
                    break;
                }
                None => {
                    self.current = self.end_of_input;
                    break;
                }
            }
        }
    }
    fn advance_with_error(
        &mut self,
        diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>,
        diag: <Self as ParserCallbacks<'a>>::Diagnostic,
    ) {
        self.error(diags, diag);
        if self.error_node.is_none() {
            self.error_node = Some(self.cst.data.open());
        }
        self.advance(true, diags);
    }
    fn peek(&self, lookahead: usize) -> Token {
        self.tokens
            .iter()
            .skip(self.pos)
            .filter(|token| !Self::is_skipped(**token))
            .nth(lookahead)
            .map_or(self.end_of_input, |it| *it)
    }
    fn peek_left(&self, lookbehind: usize) -> Token {
        self.tokens
            .iter()
            .take(self.pos + 1)
            .rev()
            .filter(|token| !Self::is_skipped(**token))
            .nth(lookbehind)
            .map_or(self.end_of_input, |it| *it)
    }
    fn close_error_node(&mut self, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) {
        if let Some(error_node) = self.error_node {
            self.cst.data.close(error_node, Rule::Error);
            self.create_node_error(NodeRef(error_node.0), diags);
            self.error_node = None;
        }
    }
    fn open(&mut self, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) -> MarkOpened {
        self.close_error_node(diags);
        self.cst.data.open()
    }
    fn open_before(
        &mut self,
        mark: MarkClosed,
        diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>,
    ) -> MarkOpened {
        self.close_error_node(diags);
        self.cst.data.open_before(mark)
    }
    fn close(
        &mut self,
        mark: MarkOpened,
        rule: Rule,
        diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>,
    ) -> MarkClosed {
        self.close_error_node(diags);
        self.cst.data.close(mark, rule)
    }
    fn close_root(
        &mut self,
        mark: MarkOpened,
        rule: Rule,
        diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>,
    ) -> MarkClosed {
        self.close_error_node(diags);
        self.cst.data.close_root(mark, rule)
    }
    fn mark(&mut self, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) -> MarkClosed {
        self.close_error_node(diags);
        self.cst.data.mark()
    }
    fn span(&self) -> Span {
        self.cst
            .data
            .spans
            .get(self.pos)
            .map_or(self.max_offset..self.max_offset, |span| span.clone())
    }
    fn get_state(&self, diags: &[<Self as ParserCallbacks<'a>>::Diagnostic]) -> ParserState {
        ParserState {
            pos: self.pos,
            current: self.current,
            truncation_mark: self.cst.data.mark_truncation(),
            diag_count: diags.len(),
        }
    }
    fn set_state(
        &mut self,
        state: &ParserState,
        diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>,
    ) {
        self.pos = state.pos;
        self.current = state.current;
        diags.truncate(state.diag_count);
        for i in state.truncation_mark.node_count..self.cst.data.nodes.len() {
            if let Node::Rule(rule, _) = self.cst.data.nodes[i] {
                self.delete_node(rule, NodeRef(i));
            }
        }
        self.cst.data.truncate(state.truncation_mark.clone());
    }
    fn create_node(
        &mut self,
        rule: Rule,
        node_ref: NodeRef,
        diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>,
    ) {
        match rule {
            Rule::Array => self.create_node_array(node_ref, diags),
            Rule::ArrayTail => self.create_node_array_tail(node_ref, diags),
            Rule::Document => self.create_node_document(node_ref, diags),
            Rule::Error => self.create_node_error(node_ref, diags),
            Rule::InlineTable => self.create_node_inline_table(node_ref, diags),
            Rule::Key => self.create_node_key(node_ref, diags),
            Rule::KeyPart => self.create_node_key_part(node_ref, diags),
            Rule::KeyValue => self.create_node_key_value(node_ref, diags),
            Rule::Statement => self.create_node_statement(node_ref, diags),
            Rule::TableTail => self.create_node_table_tail(node_ref, diags),
            Rule::Value => self.create_node_value(node_ref, diags),
        }
    }
    fn delete_node(&mut self, _rule: Rule, _node_ref: NodeRef) {}
    pub fn new_with_context(
        source: &'a str,
        diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>,
        mut context: <Self as ParserCallbacks<'a>>::Context,
    ) -> Parser<'a> {
        let (tokens, spans) = Self::create_tokens(&mut context, source, diags);
        let max_offset = source.len();
        Self {
            current: Token::EOF,
            end_of_input: Token::EOF,
            cst: Cst {
                data: CstData::new(spans),
                source,
            },
            tokens,
            pos: 0,
            max_offset,
            context,
            error_node: None,
            in_ordered_choice: false,
            error_since_advance: false,
        }
    }
    pub fn new(
        source: &'a str,
        diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>,
    ) -> Parser<'a>
    where
        <Self as ParserCallbacks<'a>>::Context: Default,
    {
        #[allow(clippy::unit_arg)]
        Self::new_with_context(
            source,
            diags,
            <Self as ParserCallbacks<'a>>::Context::default(),
        )
    }
    fn parse_rule<
        RuleParser: Fn(&mut Self, &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>),
    >(
        mut self,
        rule: RuleParser,
        diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>,
        root: Rule,
    ) -> Cst<'a> {
        let token_count = self.tokens.len();
        let m = self.open(diags);
        self.init_skip();

        rule(&mut self, diags);

        self.close_error_node(diags);
        if self.pos != token_count {
            self.error(diags, err![self, "invalid syntax, expected: <end of file>"]);
            let error_tree = self.open(diags);
            while self.pos < token_count {
                let token = self.tokens[self.pos];
                self.cst.data.advance(token, Self::is_skipped(token));
                self.pos += 1;
            }
            self.cst.data.close(error_tree, Rule::Error);
            self.create_node_error(NodeRef(error_tree.0), diags);
        }

        let closed = self.cst.data.close_root(m, root);
        self.create_node(root, NodeRef(closed.0), diags);
        self.cst
    }
    /// Returns the CST for a parse of the start rule
    pub fn parse(self, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) -> Cst<'a> {
        self.parse_rule(
            |parser, diags| parser.rule_document(diags),
            diags,
            Rule::Document,
        )
    }
    fn rule_document(&mut self, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) {
        loop {
            match self.current {
                Token::Atom | Token::LBracket | Token::Newline | Token::String => {
                    match self.current {
                        Token::Newline => {
                            expect!(Newline, "invalid syntax, expected: Newline", self, diags);
                        }
                        Token::Atom | Token::LBracket | Token::String => {
                            self.rule_statement(diags);
                            expect!(Newline, "invalid syntax, expected: Newline", self, diags);
                        }
                        _ => {
                            self.error(diags, err![self, "invalid syntax, expected one of: <atom>, \'[\', \'Newline\', <string>"]);
                        }
                    }
                }
                Token::EOF => break,
                _ => {
                    self.advance_with_error(diags, err![self, "invalid syntax, expected one of: <atom>, <end of file>, \'[\', \'Newline\', <string>"]);
                }
            }
        }
    }
    fn rule_statement(&mut self, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) {
        match self.current {
            Token::LBracket => {
                expect!(LBracket, "invalid syntax, expected: \'[\'", self, diags);
                self.rule_table_tail(diags);
            }
            Token::Atom | Token::String => {
                self.rule_key_value(diags);
            }
            _ => {
                self.error(
                    diags,
                    err![
                        self,
                        "invalid syntax, expected one of: <atom>, \'[\', <string>"
                    ],
                );
            }
        }
    }
    fn rule_table_tail(&mut self, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) {
        let m = self.open(diags);
        match self.current {
            Token::LBracket => {
                expect!(LBracket, "invalid syntax, expected: \'[\'", self, diags);
                self.rule_key(diags);
                expect!(RBracket, "invalid syntax, expected: \']\'", self, diags);
                expect!(RBracket, "invalid syntax, expected: \']\'", self, diags);
            }
            Token::Atom | Token::String => {
                self.rule_key(diags);
                expect!(RBracket, "invalid syntax, expected: \']\'", self, diags);
            }
            _ => {
                self.error(
                    diags,
                    err![
                        self,
                        "invalid syntax, expected one of: <atom>, \'[\', <string>"
                    ],
                );
            }
        }
        let closed = self.close(m, Rule::TableTail, diags);
        self.create_node_table_tail(NodeRef(closed.0), diags);
    }
    fn rule_key_value(&mut self, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) {
        let m = self.open(diags);
        self.rule_key(diags);
        expect!(Equals, "invalid syntax, expected: \'=\'", self, diags);
        self.rule_value(diags);
        let closed = self.close(m, Rule::KeyValue, diags);
        self.create_node_key_value(NodeRef(closed.0), diags);
    }
    fn rule_key(&mut self, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) {
        let m = self.open(diags);
        self.rule_key_part(diags);
        loop {
            match self.current {
                Token::Dot => {
                    expect!(Dot, "invalid syntax, expected: \'.\'", self, diags);
                    self.rule_key_part(diags);
                }
                Token::Equals | Token::RBracket => break,
                Token::Atom | Token::EOF | Token::LBracket | Token::Newline | Token::String => {
                    self.error(
                        diags,
                        err![self, "invalid syntax, expected one of: \'.\', \'=\', \']\'"],
                    );
                    break;
                }
                _ => {
                    self.advance_with_error(
                        diags,
                        err![self, "invalid syntax, expected one of: \'.\', \'=\', \']\'"],
                    );
                }
            }
        }
        let closed = self.close(m, Rule::Key, diags);
        self.create_node_key(NodeRef(closed.0), diags);
    }
    fn rule_key_part(&mut self, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) {
        let m = self.open(diags);
        match self.current {
            Token::String => {
                expect!(String, "invalid syntax, expected: <string>", self, diags);
            }
            Token::Atom => {
                expect!(Atom, "invalid syntax, expected: <atom>", self, diags);
            }
            _ => {
                self.error(
                    diags,
                    err![self, "invalid syntax, expected one of: <atom>, <string>"],
                );
            }
        }
        let closed = self.close(m, Rule::KeyPart, diags);
        self.create_node_key_part(NodeRef(closed.0), diags);
    }
    fn rule_value(&mut self, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) {
        match self.current {
            Token::String => {
                expect!(String, "invalid syntax, expected: <string>", self, diags);
            }
            Token::Atom => {
                expect!(Atom, "invalid syntax, expected: <atom>", self, diags);
            }
            Token::LBracket => {
                self.rule_array(diags);
            }
            Token::LBrace => {
                self.rule_inline_table(diags);
            }
            _ => {
                self.error(
                    diags,
                    err![
                        self,
                        "invalid syntax, expected one of: <atom>, \'{\', \'[\', <string>"
                    ],
                );
            }
        }
    }
    fn rule_array(&mut self, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) {
        let m = self.open(diags);
        expect!(LBracket, "invalid syntax, expected: \'[\'", self, diags);
        loop {
            match self.current {
                Token::Atom | Token::LBrace | Token::LBracket | Token::String => {
                    self.rule_value(diags);
                    loop {
                        match self.current {
                            Token::Comma => {
                                self.rule_array_tail(diags);
                                break;
                            }
                            Token::RBracket => break,
                            Token::Atom
                            | Token::EOF
                            | Token::LBracket
                            | Token::Newline
                            | Token::RBrace
                            | Token::String => {
                                self.error(
                                    diags,
                                    err![self, "invalid syntax, expected one of: \',\', \']\'"],
                                );
                                break;
                            }
                            _ => {
                                self.advance_with_error(
                                    diags,
                                    err![self, "invalid syntax, expected one of: \',\', \']\'"],
                                );
                            }
                        }
                    }
                    break;
                }
                Token::RBracket => break,
                Token::Comma | Token::EOF | Token::Newline | Token::RBrace => {
                    self.error(
                        diags,
                        err![
                            self,
                            "invalid syntax, expected one of: <atom>, \'{\', \'[\', \']\', <string>"
                        ],
                    );
                    break;
                }
                _ => {
                    self.advance_with_error(
                        diags,
                        err![
                            self,
                            "invalid syntax, expected one of: <atom>, \'{\', \'[\', \']\', <string>"
                        ],
                    );
                }
            }
        }
        expect!(RBracket, "invalid syntax, expected: \']\'", self, diags);
        let closed = self.close(m, Rule::Array, diags);
        self.create_node_array(NodeRef(closed.0), diags);
    }
    fn rule_array_tail(&mut self, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) {
        let m = self.open(diags);
        expect!(Comma, "invalid syntax, expected: \',\'", self, diags);
        loop {
            match self.current {
                Token::Atom | Token::LBrace | Token::LBracket | Token::String => {
                    self.rule_value(diags);
                    loop {
                        match self.current {
                            Token::Comma => {
                                self.rule_array_tail(diags);
                                break;
                            }
                            Token::RBracket => break,
                            Token::Atom
                            | Token::EOF
                            | Token::LBracket
                            | Token::Newline
                            | Token::RBrace
                            | Token::String => {
                                self.error(
                                    diags,
                                    err![self, "invalid syntax, expected one of: \',\', \']\'"],
                                );
                                break;
                            }
                            _ => {
                                self.advance_with_error(
                                    diags,
                                    err![self, "invalid syntax, expected one of: \',\', \']\'"],
                                );
                            }
                        }
                    }
                    break;
                }
                Token::RBracket => break,
                Token::Comma | Token::EOF | Token::Newline | Token::RBrace => {
                    self.error(
                        diags,
                        err![
                            self,
                            "invalid syntax, expected one of: <atom>, \'{\', \'[\', \']\', <string>"
                        ],
                    );
                    break;
                }
                _ => {
                    self.advance_with_error(
                        diags,
                        err![
                            self,
                            "invalid syntax, expected one of: <atom>, \'{\', \'[\', \']\', <string>"
                        ],
                    );
                }
            }
        }
        let closed = self.close(m, Rule::ArrayTail, diags);
        self.create_node_array_tail(NodeRef(closed.0), diags);
    }
    fn rule_inline_table(&mut self, diags: &mut Vec<<Self as ParserCallbacks<'a>>::Diagnostic>) {
        let m = self.open(diags);
        expect!(LBrace, "invalid syntax, expected: \'{\'", self, diags);
        loop {
            match self.current {
                Token::Atom | Token::String => {
                    self.rule_key_value(diags);
                    loop {
                        match self.current {
                            Token::Comma => {
                                expect!(Comma, "invalid syntax, expected: \',\'", self, diags);
                                self.rule_key_value(diags);
                            }
                            Token::RBrace => break,
                            Token::Atom
                            | Token::EOF
                            | Token::LBracket
                            | Token::Newline
                            | Token::RBracket
                            | Token::String => {
                                self.error(
                                    diags,
                                    err![self, "invalid syntax, expected one of: \',\', \'}\'"],
                                );
                                break;
                            }
                            _ => {
                                self.advance_with_error(
                                    diags,
                                    err![self, "invalid syntax, expected one of: \',\', \'}\'"],
                                );
                            }
                        }
                    }
                    break;
                }
                Token::RBrace => break,
                Token::Comma | Token::EOF | Token::LBracket | Token::Newline | Token::RBracket => {
                    self.error(
                        diags,
                        err![
                            self,
                            "invalid syntax, expected one of: <atom>, \'}\', <string>"
                        ],
                    );
                    break;
                }
                _ => {
                    self.advance_with_error(
                        diags,
                        err![
                            self,
                            "invalid syntax, expected one of: <atom>, \'}\', <string>"
                        ],
                    );
                }
            }
        }
        expect!(RBrace, "invalid syntax, expected: \'}\'", self, diags);
        let closed = self.close(m, Rule::InlineTable, diags);
        self.create_node_inline_table(NodeRef(closed.0), diags);
    }
}

#[allow(clippy::ptr_arg)]
pub trait ParserCallbacks<'a> {
    type Diagnostic;
    type Context;

    /// Called at the start of the parse to generate all tokens and corresponding spans.
    fn create_tokens(
        context: &mut Self::Context,
        source: &'a str,
        diags: &mut Vec<Self::Diagnostic>,
    ) -> (Vec<Token>, Vec<Span>);
    /// Called when diagnostic is created.
    fn create_diagnostic(&self, span: Span, message: String) -> Self::Diagnostic;
    /// This predicate can be used to skip normal tokens.
    fn predicate_skip(&self, _token: Token) -> bool {
        false
    }

    /// Called when `array` node is created.
    fn create_node_array(&mut self, _node_ref: NodeRef, _diags: &mut Vec<Self::Diagnostic>) {}
    /// Called when `array_tail` node is created.
    fn create_node_array_tail(&mut self, _node_ref: NodeRef, _diags: &mut Vec<Self::Diagnostic>) {}
    /// Called when `document` node is created.
    fn create_node_document(&mut self, _node_ref: NodeRef, _diags: &mut Vec<Self::Diagnostic>) {}
    /// Called when `error` node is created.
    fn create_node_error(&mut self, _node_ref: NodeRef, _diags: &mut Vec<Self::Diagnostic>) {}
    /// Called when `inline_table` node is created.
    fn create_node_inline_table(&mut self, _node_ref: NodeRef, _diags: &mut Vec<Self::Diagnostic>) {
    }
    /// Called when `key` node is created.
    fn create_node_key(&mut self, _node_ref: NodeRef, _diags: &mut Vec<Self::Diagnostic>) {}
    /// Called when `key_part` node is created.
    fn create_node_key_part(&mut self, _node_ref: NodeRef, _diags: &mut Vec<Self::Diagnostic>) {}
    /// Called when `key_value` node is created.
    fn create_node_key_value(&mut self, _node_ref: NodeRef, _diags: &mut Vec<Self::Diagnostic>) {}
    /// Called when `statement` node is created.
    fn create_node_statement(&mut self, _node_ref: NodeRef, _diags: &mut Vec<Self::Diagnostic>) {}
    /// Called when `table_tail` node is created.
    fn create_node_table_tail(&mut self, _node_ref: NodeRef, _diags: &mut Vec<Self::Diagnostic>) {}
    /// Called when `value` node is created.
    fn create_node_value(&mut self, _node_ref: NodeRef, _diags: &mut Vec<Self::Diagnostic>) {}
}

mod support;
