[package]
name = "telora-run"
version.workspace = true
edition.workspace = true

[dependencies]
bytes = "1"
http-body-util = "0.1"
hyper = { version = "1", features = ["server", "http1"] }
hyper-util = { version = "0.1", features = ["tokio"] }
tokio = { version = "1", features = ["rt", "net", "time", "sync", "macros"] }
futures = "0.3"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["raw_value"] }
wasmparser = "0.259"
wasmi = "2"
telora-wasm-shared = { path = "../telora-wasm-shared" }
